create table if not exists public.user_profiles (
  email text primary key,
  friend_code text unique not null default upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)),
  name text,
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gustambito_progress (
  email text not null references public.user_profiles(email) on delete cascade,
  gustambito_id integer not null,
  variant_label text not null,
  level integer not null default 0 check (level between 0 and 5),
  updated_at timestamptz not null default now(),
  primary key (email, gustambito_id, variant_label)
);

alter table public.user_profiles enable row level security;
alter table public.gustambito_progress enable row level security;

alter table public.user_profiles add column if not exists friend_code text;
update public.user_profiles set friend_code = upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)) where friend_code is null;
alter table public.user_profiles alter column friend_code set not null;
create unique index if not exists user_profiles_friend_code_idx on public.user_profiles(friend_code);

create table if not exists public.user_friends (
  owner_email text not null references public.user_profiles(email) on delete cascade,
  friend_email text not null references public.user_profiles(email) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (owner_email, friend_email),
  check (owner_email <> friend_email)
);

alter table public.user_friends enable row level security;

create table if not exists public.fortnite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  reward text not null,
  category text not null default 'OTROS',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.fortnite_codes add column if not exists category text not null default 'OTROS';

create table if not exists public.user_used_fortnite_codes (
  email text not null references public.user_profiles(email) on delete cascade,
  code_id bigint not null references public.fortnite_codes(id) on delete cascade,
  used_at timestamptz not null default now(),
  primary key (email, code_id)
);

create table if not exists public.user_wrixel_parts (
  email text not null references public.user_profiles(email) on delete cascade,
  part_key text not null,
  collected boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (email, part_key)
);

alter table public.fortnite_codes enable row level security;
alter table public.user_used_fortnite_codes enable row level security;
alter table public.user_wrixel_parts enable row level security;

grant select, insert, update, delete on public.fortnite_codes, public.user_used_fortnite_codes to service_role;
grant select, insert, update, delete on public.user_wrixel_parts to service_role;
grant usage, select on sequence public.fortnite_codes_id_seq to service_role;

update public.fortnite_codes
set active = false, updated_at = now()
where upper(code) not in (
  'OVERRIDEXP','PERLIMPINPIN','CHISPAMBO','ABGESTAUBT','MAGILUME',
  'O2OVERRIDE','TAKEYOURHEART','PERFECTORDER','SURVIVETHENIGHT','FINDITCHAT',
  'BORN2PLAY','8BITBLAST','IWANNAFLYHIGH','GOTTAGOFAST','PLAY4ALL','GATHERANDCRAFT',
  'BEMOREALIEN','REACHYOURIMPOSSIBLE','LETSBLOCKANDROLL','DONTBLOCKME'
);

insert into public.fortnite_codes (code, reward, category) values
  ('OVERRIDEXP', '40,000 PE', 'CÓDIGOS DE PE'),
  ('PERLIMPINPIN', '2,000 Polvo de Espíritus', 'CÓDIGOS DE POLVO DE ESPÍRITUS'),
  ('CHISPAMBO', '2,000 Polvo de Espíritus', 'CÓDIGOS DE POLVO DE ESPÍRITUS'),
  ('ABGESTAUBT', '2,000 Polvo de Espíritus', 'CÓDIGOS DE POLVO DE ESPÍRITUS'),
  ('MAGILUME', 'Polvo de Espíritus infinito… o tal vez no', 'CÓDIGOS DE POLVO DE ESPÍRITUS'),
  ('O2OVERRIDE', 'Entrega de suministro de llama + 5 Extractores portátiles', 'CÓDIGOS DE ARTILUGIOS'),
  ('TAKEYOURHEART', '2 Aceleradores de Extracción', 'CÓDIGOS DE ARTILUGIOS'),
  ('PERFECTORDER', '4 Tacos picantes', 'CÓDIGOS DE ARTILUGIOS'),
  ('SURVIVETHENIGHT', '2 Localizadores de códigos', 'CÓDIGOS DE ARTILUGIOS'),
  ('FINDITCHAT', '2 Localizadores de códigos', 'CÓDIGOS DE ARTILUGIOS'),
  ('BORN2PLAY', 'Espíritu Aventurero hacker (variante)', 'CÓDIGOS DE ESPÍRITUS'),
  ('8BITBLAST', 'Espíritu de 8 bits hacker (variante)', 'CÓDIGOS DE ESPÍRITUS'),
  ('IWANNAFLYHIGH', 'Espíritu de Tails hacker (variante)', 'CÓDIGOS DE ESPÍRITUS'),
  ('GOTTAGOFAST', 'Espíritu de Sonic hacker (variante)', 'CÓDIGOS DE ESPÍRITUS'),
  ('PLAY4ALL', 'Espíritu de Jonesy hacker (variante)', 'CÓDIGOS DE ESPÍRITUS'),
  ('GATHERANDCRAFT', 'Espíritu de Arbustín hacker (variante). Puede requerir completar la primera tanda de Historia.', 'CÓDIGOS DE ESPÍRITUS'),
  ('BEMOREALIEN', 'Pantalla de carga “Glitch activo”', 'CÓDIGOS DE COSMÉTICOS'),
  ('REACHYOURIMPOSSIBLE', 'Pantalla de carga “Fiesta de Bloques”', 'CÓDIGOS DE COSMÉTICOS'),
  ('LETSBLOCKANDROLL', 'Transformación en bloque de Tetris en el lobby', 'CÓDIGOS DE EFECTOS DE SALA DE ESPERA'),
  ('DONTBLOCKME', 'Transformación en bloque de Tetris en el lobby', 'CÓDIGOS DE EFECTOS DE SALA DE ESPERA')
on conflict (code) do update set reward = excluded.reward, category = excluded.category, active = true, updated_at = now();

drop policy if exists "realtime can read progress" on public.gustambito_progress;
create policy "realtime can read progress"
  on public.gustambito_progress
  for select
  to anon, authenticated
  using (true);

grant usage on schema public to service_role;
grant select, insert, update, delete on public.user_profiles, public.gustambito_progress, public.user_friends, public.fortnite_codes, public.user_used_fortnite_codes, public.user_wrixel_parts to service_role;
grant select on public.gustambito_progress to anon, authenticated;
drop trigger if exists gustambito_progress_broadcast on public.gustambito_progress;
drop function if exists public.broadcast_gustambito_progress();
alter table public.gustambito_progress replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.gustambito_progress;
exception when duplicate_object then
  null;
end $$;
