create table if not exists public.user_profiles (
  email text primary key,
  friend_code text unique not null default upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)),
  name text,
  image text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gustambito_progress (
  email text not null references public.user_profiles(email) on delete cascade,
  gustambito_id integer not null,
  variant_label text not null,
  level integer not null default 0 check (level between 0 and 5),
  updated_at timestamptz not null default now(),
  primary key (email, gustambito_id, variant_label)
);

alter table public.user_profiles enable row level security;
alter table public.gustambito_progress enable row level security;

alter table public.user_profiles add column if not exists friend_code text;
update public.user_profiles set friend_code = upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)) where friend_code is null;
alter table public.user_profiles alter column friend_code set not null;
create unique index if not exists user_profiles_friend_code_idx on public.user_profiles(friend_code);

create table if not exists public.user_friends (
  owner_email text not null references public.user_profiles(email) on delete cascade,
  friend_email text not null references public.user_profiles(email) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (owner_email, friend_email),
  check (owner_email <> friend_email)
);

alter table public.user_friends enable row level security;

create table if not exists public.fortnite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  reward text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.user_used_fortnite_codes (
  email text not null references public.user_profiles(email) on delete cascade,
  code_id bigint not null references public.fortnite_codes(id) on delete cascade,
  used_at timestamptz not null default now(),
  primary key (email, code_id)
);

create table if not exists public.user_wrixel_parts (
  email text not null references public.user_profiles(email) on delete cascade,
  part_key text not null,
  collected boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (email, part_key)
);

alter table public.fortnite_codes enable row level security;
alter table public.user_used_fortnite_codes enable row level security;
alter table public.user_wrixel_parts enable row level security;

grant select, insert, update, delete on public.fortnite_codes, public.user_used_fortnite_codes to service_role;
grant select, insert, update, delete on public.user_wrixel_parts to service_role;
grant usage, select on sequence public.fortnite_codes_id_seq to service_role;

insert into public.fortnite_codes (code, reward) values
  ('OVERRIDEXP', '40,000 PE'),
  ('PERLIMPINPIN', '2,000 Polvo de Espíritus'),
  ('CHISPAMBO', '2,000 Polvo de Espíritus'),
  ('ABGESTAUBT', '2,000 Polvo de Espíritus'),
  ('MAGILUME', 'Polvo de Espíritus infinito… o tal vez no'),
  ('O2OVERRIDE', 'Entrega de suministro de llama + 5 Extractores portátiles'),
  ('TAKEYOURHEART', '2 Aceleradores de Extracción'),
  ('PERFECTORDER', '4 Tacos picantes'),
  ('SURVIVETHENIGHT', '2 Localizadores de códigos'),
  ('FINDITCHAT', '2 Localizadores de códigos'),
  ('BORN2PLAY', 'Espíritu Aventurero hacker (variante)'),
  ('8BITBLAST', 'Espíritu de 8 bits hacker (variante)'),
  ('IWANNAFLYHIGH', 'Espíritu de Tails hacker (variante)'),
  ('GOTTAGOFAST', 'Espíritu de Sonic hacker (variante)'),
  ('PLAY4ALL', 'Espíritu de Jonesy hacker (variante)'),
  ('GATHERANDCRAFT', 'Espíritu de Arbustín hacker (variante). Puede requerir completar la primera tanda de Historia.'),
  ('BEMOREALIEN', 'Pantalla de carga “Glitch activo”'),
  ('REACHYOURIMPOSSIBLE', 'Pantalla de carga “Fiesta de Bloques”'),
  ('LETSBLOCKANDROLL', 'Transformación en bloque de Tetris en el lobby'),
  ('DONTBLOCKME', 'Transformación en bloque de Tetris en el lobby'),
  ('JONESYISGOLDEN', 'Espíritu Jonesy dorado (variante)'),
  ('h0p0nvc', '2,000 Polvo de Espíritus · Los 0 son ceros'),
  ('INVALIDCHEAT', '2 Localizadores de códigos'),
  ('ChatWhereDoYouFindTheKey', '2 Aceleradores de Extracción'),
  ('YourThoughtsAreMine', '5,000 Polvo de Espíritus · Requiere la misión oculta de Geno')
on conflict (code) do nothing;

drop policy if exists "realtime can read progress" on public.gustambito_progress;
create policy "realtime can read progress"
  on public.gustambito_progress
  for select
  to anon, authenticated
  using (true);

grant usage on schema public to service_role;
grant select, insert, update, delete on public.user_profiles, public.gustambito_progress, public.user_friends, public.fortnite_codes, public.user_used_fortnite_codes, public.user_wrixel_parts to service_role;
grant select on public.gustambito_progress to anon, authenticated;
drop trigger if exists gustambito_progress_broadcast on public.gustambito_progress;
drop function if exists public.broadcast_gustambito_progress();
alter table public.gustambito_progress replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.gustambito_progress;
exception when duplicate_object then
  null;
end $$;
