"use client";

import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import { signIn, signOut, useSession } from "next-auth/react";

type Variant = { label: string; image: string; level: number };
type Gustambito = { id: number; name: string; subtitle: string; rarity: "Mítico" | "Épico" | "Raro"; color: string; image: string; season: string; variants: Variant[] };
type VariantCard = { item: Gustambito; variant: Variant; variantIndex: number };
type Friend = { email: string; name: string | null; image: string | null; friend_code: string; progress: { gustambito_id: number; variant_label: string; level: number }[] };

const spriteUrl = (key: string, variant = "") => `https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_${key}${variant ? `_${variant}` : ""}_L.webp`;
const makeVariants = (key: string, levels: number[] = [0, 0, 0]): Variant[] => [
  { label: "Base", image: spriteUrl(key), level: levels[0] },
  { label: "Dorado", image: spriteUrl(key, "Gold"), level: levels[1] },
  { label: "Cheat Master", image: spriteUrl(key, "Cheatmaster"), level: levels[2] },
];
const initialGustambitos: Gustambito[] = [
  { id: 1, name: "Jackrabbit", subtitle: "Salta más lejos", rarity: "Raro", color: "#8ed35b", image: spriteUrl("JazzJackrabbit"), season: "GLITCH · Capítulo 7", variants: makeVariants("JazzJackrabbit") },
  { id: 2, name: "Shadow", subtitle: "Se mueve entre las sombras", rarity: "Épico", color: "#5b4e74", image: spriteUrl("NarrowFlea_Scribe"), season: "GLITCH · Capítulo 7", variants: makeVariants("NarrowFlea_Scribe") },
  { id: 3, name: "Bush", subtitle: "Se camufla en la isla", rarity: "Raro", color: "#79c85b", image: spriteUrl("BushRanger"), season: "GLITCH · Capítulo 7", variants: makeVariants("BushRanger") },
  { id: 4, name: "Tails", subtitle: "El compañero volador", rarity: "Épico", color: "#e98b42", image: spriteUrl("NarrowFlea_Monkey"), season: "GLITCH · Capítulo 7", variants: makeVariants("NarrowFlea_Monkey") },
  { id: 5, name: "Killswitch", subtitle: "Controla el sistema", rarity: "Épico", color: "#94a5a1", image: spriteUrl("Killswitch"), season: "GLITCH · Capítulo 7", variants: makeVariants("Killswitch") },
  { id: 6, name: "Adventure", subtitle: "Siempre busca el siguiente nivel", rarity: "Épico", color: "#c47f48", image: spriteUrl("Dwarf"), season: "GLITCH · Capítulo 7", variants: makeVariants("Dwarf") },
  { id: 7, name: "Klombo", subtitle: "El gigante amistoso", rarity: "Mítico", color: "#ef63c4", image: spriteUrl("Klombo"), season: "GLITCH · Capítulo 7", variants: makeVariants("Klombo") },
  { id: 8, name: "Jonesy", subtitle: "El héroe de siempre", rarity: "Épico", color: "#ef7b5b", image: spriteUrl("Jonesy"), season: "GLITCH · Capítulo 7", variants: makeVariants("Jonesy") },
  { id: 9, name: "Sonic", subtitle: "Corre a velocidad sónica", rarity: "Mítico", color: "#55b7ed", image: spriteUrl("NarrowFlea_Obsidian"), season: "GLITCH · Capítulo 7", variants: makeVariants("NarrowFlea_Obsidian") },
  { id: 10, name: "Crown", subtitle: "Realeza en el lobby", rarity: "Mítico", color: "#e6534e", image: spriteUrl("Crown"), season: "GLITCH · Capítulo 7", variants: makeVariants("Crown") },
  { id: 11, name: "8-Bit", subtitle: "Directo desde el arcade", rarity: "Épico", color: "#e86552", image: spriteUrl("EightBitBlaster"), season: "GLITCH · Capítulo 7", variants: makeVariants("EightBitBlaster") },
  { id: 12, name: "Storm Scout", subtitle: "Descubre el siguiente círculo", rarity: "Raro", color: "#a775dd", image: spriteUrl("StormScout"), season: "GLITCH · Capítulo 7", variants: makeVariants("StormScout") },
];

const migrate = (value: Gustambito[]): Gustambito[] => value.map((item) => ({ ...item, variants: item.variants.map((variant) => ({ ...variant, level: typeof variant.level === "number" ? variant.level : ("obtained" in variant && variant.obtained ? 1 : 0) })) }));

function LoginScreen() {
  return <main className="login-screen"><div className="login-glow" /><div className="login-card"><div className="brand login-brand"><span className="brand-mark">G</span><span>GUSTAMBITOS</span></div><p className="eyebrow">GLITCH · TEMPORADA 04</p><div className="login-mascot">♛</div><h1>Tu colección<br /><em>empieza aquí.</em></h1><p className="login-copy">Inicia sesión para guardar tus niveles, variantes y Gustambitos dominados.</p><button className="google-button" onClick={() => signIn("google")}><span className="google-icon">G</span>Continuar con Google</button><small className="login-note">Tu progreso quedará asociado a tu cuenta.</small></div></main>;
}

export default function Home() {
  const { status, data: session } = useSession();
  const [gustambitos, setGustambitos] = useState(initialGustambitos);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("Todos");
  const [hydrated, setHydrated] = useState(false);
  const [friends, setFriends] = useState<Friend[]>([]);
  const [myFriendCode, setMyFriendCode] = useState("");
  const [friendInput, setFriendInput] = useState("");
  const [selectedFriend, setSelectedFriend] = useState<Friend | null>(null);
  const [showFriends, setShowFriends] = useState(false);
  const [showProfile, setShowProfile] = useState(false);
  const [friendError, setFriendError] = useState("");
  const accountStorageKey = `gustambitos-glitch-v4-${session?.user?.email ?? "guest"}`;
  useEffect(() => { if (status !== "authenticated" || !session?.user?.email) return; const sync = async () => { const response = await fetch("/api/progress"); if (response.ok) { const { progress } = await response.json(); if (progress.length) setGustambitos((current) => current.map((item) => ({ ...item, variants: item.variants.map((variant) => { const saved = progress.find((entry: { gustambito_id: number; variant_label: string; level: number }) => entry.gustambito_id === item.id && entry.variant_label === variant.label); return saved ? { ...variant, level: saved.level } : variant; }) }))); } else { const saved = window.localStorage.getItem(accountStorageKey); if (saved) setGustambitos(migrate(JSON.parse(saved))); } window.requestAnimationFrame(() => setHydrated(true)); }; sync(); }, [status, session?.user?.email, accountStorageKey]);
  useEffect(() => { if (status === "authenticated") void fetch("/api/progress").then(() => fetch("/api/friends")).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error || "No se pudo cargar tu ID"); setMyFriendCode(data.profile.friend_code); setFriends(data.friends); }).catch((error: Error) => setFriendError(error.message)); }, [status]);
  const visible = hydrated ? gustambitos : initialGustambitos;
  const setLevel = (id: number, variantIndex: number, level: number) => { const item = gustambitos.find((entry) => entry.id === id); const variant = item?.variants[variantIndex]; const next = gustambitos.map((entry) => entry.id !== id ? entry : { ...entry, variants: entry.variants.map((current, index) => index === variantIndex ? { ...current, level } : current) }); setGustambitos(next); window.localStorage.setItem(accountStorageKey, JSON.stringify(next)); if (variant) void fetch("/api/progress", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ gustambitoId: id, variantLabel: variant.label, level }) }); };
  const cards = useMemo<VariantCard[]>(() => visible.flatMap((item) => item.variants.map((variant, variantIndex) => ({ item, variant, variantIndex }))), [visible]);
  const filtered = useMemo(() => cards.filter(({ item, variant }) => (filter === "Todos" || (filter === "Conseguidos" ? variant.level > 0 : item.rarity === filter)) && `${item.name} ${variant.label}`.toLowerCase().includes(query.toLowerCase())), [cards, filter, query]);
  const collected = cards.filter(({ variant }) => variant.level > 0).length;
  const mastered = cards.filter(({ variant }) => variant.level === 5).length;
  const progress = Math.round((collected / cards.length) * 100);
  const addFriend = async () => { setFriendError(""); const response = await fetch("/api/friends", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ friendCode: friendInput }) }); const data = await response.json(); if (!response.ok) return setFriendError(data.error); setFriendInput(""); const refreshed = await fetch("/api/friends").then((result) => result.json()); setMyFriendCode(refreshed.profile.friend_code); setFriends(refreshed.friends); };
  const friendVariants = selectedFriend ? initialGustambitos.flatMap((item) => item.variants.map((variant) => ({ item, variant, level: selectedFriend.progress.find((entry) => entry.gustambito_id === item.id && entry.variant_label === variant.label)?.level ?? 0 }))) : [];

  if (status !== "authenticated") return <LoginScreen />;

  return <main className="shell">
    <nav className="topbar"><div className="brand"><span className="brand-mark">G</span><span>GUSTAMBITOS</span></div><div className="season-pill"><span className="live-dot" /> GLITCH · TEMPORADA 04 <span className="season-arrow">⌄</span></div><div className="top-actions"><button className="friends-button" onClick={() => setShowFriends(true)}>AMIGOS <span>{friends.length}</span></button><button className="profile" onClick={() => setShowProfile(true)} aria-label="Abrir perfil de usuario">{session?.user?.image ? <img src={session.user.image} alt={session.user.name ? `Foto de ${session.user.name}` : "Foto de perfil"} /> : "L"}<span /></button></div></nav>
    {showProfile && <div className="profile-overlay" role="dialog" aria-modal="true" aria-label="Perfil de usuario" onClick={() => setShowProfile(false)}><aside className="profile-drawer" onClick={(event) => event.stopPropagation()}><button className="close-friends" onClick={() => setShowProfile(false)} aria-label="Cerrar">×</button><p className="eyebrow">CUENTA · GLITCH</p><div className="drawer-avatar">{session?.user?.image ? <img src={session.user.image} alt="" /> : "L"}</div><h2>{session?.user?.name || "Jugador"}</h2><p className="drawer-email">{session?.user?.email}</p><div className="drawer-id-label">TU ID DE GUSTAMBITOS</div><div className="friend-code drawer-code">{myFriendCode || "--------"}<button onClick={() => navigator.clipboard?.writeText(myFriendCode)}>COPIAR</button></div>{friendError && <p className="friend-error">{friendError}</p>}<p className="friend-help">Comparte este ID para que tus amigos vean tu colección.</p><button className="signout-button" onClick={() => signOut({ callbackUrl: "/" })}>CERRAR SESIÓN</button></aside></div>}
    {showFriends && <div className="friends-overlay" role="dialog" aria-modal="true" aria-label="Amigos"><div className="friends-panel"><button className="close-friends" onClick={() => setShowFriends(false)} aria-label="Cerrar">×</button><p className="eyebrow">CONEXIONES · GLITCH</p><h2>Tu ID de amigo</h2><div className="friend-code">{myFriendCode || "--------"}<button onClick={() => navigator.clipboard?.writeText(myFriendCode)}>COPIAR</button></div><p className="friend-help">Comparte este código por WhatsApp, Facebook o donde quieras.</p><div className="add-friend"><input value={friendInput} onChange={(event) => setFriendInput(event.target.value.toUpperCase())} maxLength={8} placeholder="ID DE TU AMIGO" /><button onClick={addFriend}>AGREGAR</button></div>{friendError && <p className="friend-error">{friendError}</p>}<div className="friends-heading"><h3>Tus amigos</h3><span>{friends.length}</span></div>{friends.length === 0 ? <p className="friend-help">Todavía no tienes amigos agregados.</p> : <div className="friend-list">{friends.map((friend) => <button key={friend.email} className={`friend-row ${selectedFriend?.email === friend.email ? "selected" : ""}`} onClick={() => setSelectedFriend(friend)}><span className="friend-avatar">{(friend.name || friend.email)[0].toUpperCase()}</span><span><strong>{friend.name || "Jugador"}</strong><small>ID: {friend.friend_code}</small></span><b>VER</b></button>)}</div>}{selectedFriend && <div className="friend-collection"><h3>Colección de {selectedFriend.name || "tu amigo"}</h3><div className="friend-variants">{friendVariants.map(({ item, variant, level }) => <div className={`friend-variant ${level === 5 ? "mastered" : ""}`} key={`${item.id}-${variant.label}`}><img src={variant.image} alt={`${item.name} ${variant.label}`} /><span>{item.name} · {variant.label}</span><b>{level === 5 ? "♛" : `N${level}`}</b></div>)}</div></div>}</div></div>}
    <section className="hero"><div className="hero-copy"><p className="eyebrow">NUEVA TEMPORADA · CAPÍTULO 7</p><h1>Colecciónalos<br /><em>todos.</em></h1><p className="hero-text">Tu álbum personal de Gustambitos. Sube cada variante hasta el nivel 5 y consigue la corona de dominado.</p><div className="hero-actions"><button className="primary-button" onClick={() => document.getElementById("collection")?.scrollIntoView({ behavior: "smooth" })}>Ver colección <span>↘</span></button><span className="updated">Actualizado hoy · 20 ago 2026</span></div></div><div className="hero-orbit" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="mascot">♛</div><span className="orbit-tag tag-one">NIVEL 5 = DOMINADO</span><span className="orbit-tag tag-two">36 VARIANTES</span></div></section>
    <section className="stats-row" aria-label="Resumen de colección"><div className="stat-card progress-card"><div className="stat-label">COLECCIÓN CONSEGUIDA</div><div className="progress-number">{progress}<small>%</small></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="stat-foot"><span>{collected} conseguidas</span><span>{cards.length - collected} pendientes</span></div></div><div className="stat-card"><div className="stat-label">GUSTAMBITOS DOMINADOS</div><div className="last-found"><span className="mini-icon">♛</span><div><strong>{mastered} con corona</strong><small>Nivel máximo alcanzado</small></div></div></div><div className="stat-card streak-card"><div className="stat-label">RACHA DE COLECCIÓN</div><div className="streak">03 <span>días</span> <b>✦</b></div><small>¡Sigue así, vas volando!</small></div></section>
    <section className="collection-section" id="collection"><div className="section-heading"><div><p className="eyebrow">TU ÁLBUM · GLITCH</p><h2>Variantes de Gustambitos</h2></div><span className="count-badge">{mastered}/{cards.length} DOMINADAS</span></div><div className="toolbar"><div className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar sprite o variante..." aria-label="Buscar sprite o variante" /></div><div className="filters">{["Todos", "Conseguidos", "Mítico", "Épico", "Raro"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="grid">{filtered.map(({ item, variant, variantIndex }) => <article className={`gustambito-card ${variant.level === 5 ? "mastered-card" : ""}`} key={`${item.id}-${variant.label}`}><div className="card-visual" style={{ "--accent": item.color } as CSSProperties}><button className="card-no master-button" onClick={() => setLevel(item.id, variantIndex, 5)} aria-label="Marcar como dominado"><img src="/mastered-crown.png" alt="" /></button><img className="sprite-image" src={variant.image} alt={`${item.name} ${variant.label}`} />{variant.level === 5 && <span className="crown"><img src="/mastered-crown.png" alt="Dominado" /></span>}</div><div className="card-info"><div><h3>{item.name}</h3><p>{variant.label} · {item.subtitle}</p></div><span className="level-badge">NIVEL {variant.level}/5</span></div><div className="level-control"><span>NIVEL DE COLECCIÓN</span><div className="stepper"><button onClick={() => setLevel(item.id, variantIndex, Math.max(0, variant.level - 1))} disabled={variant.level === 0} aria-label="Bajar nivel">−</button><strong>{variant.level}</strong><button onClick={() => setLevel(item.id, variantIndex, Math.min(5, variant.level + 1))} disabled={variant.level === 5} aria-label="Subir nivel">+</button></div></div><div className="card-season">{item.season}</div></article>)}</div>{filtered.length === 0 && <div className="empty">No encontramos ese Gustambito. Prueba con otro nombre.</div>}</section>
    <footer><span>GUSTAMBITOS <i>✦</i></span><span>Nivel 5 = DOMINADO · GLITCH v1.3</span></footer>
  </main>;
}
